### PR TITLE
Remember username and logout

### PR DESCRIPTION
**Pull request by hatuongminh96**

### CODE REVIEW

**Comment by jackykc** [comment]
During sign up, we still want to put the user object on to elastic search.
At the same time, the username must be saved in a local file.
During log in, we first check if that user name is in our own local file.
If it is, then we log in by getting the object from elastic search
If it is not in our local file, then we deny login

**Comment by hatuongminh96** [comment]
Why would we want all username in a local file? Would we delete all cache when logout?

**Comment by jackykc** [comment]
We want the usernames that the CURRENT user created to be in the local file. So that we only sign into those ones. We should not be able to sign into users created by others (users not in our local file, but on elastic search)

**Comment by hatuongminh96** [comment]
That's what this branch did

**Pull request merged**
